config/routes.rb
Rails.application.routes.draw do
  get 'order/index'

  get 'order/edit'

  get 'order/new'

  get 'order/show'

  

  resources :categories
  devise_for :users
  get 'home/index'

  resources :products
  resources :order_items
  resource :carts, only: [:show]

  root "home#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true
	 has_many :has_categories
	
end
 

app/models/has_category.rb
class HasCategory < ApplicationRecord
   has_and_belongs_to_many :products
  has_and_belongs_to_many :categories
 
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity) : 0}.sum
  end

  private
  def set_subtotal
    self[:subtotal] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :user
  has_many :order_items
  attr_reader :Categories

   after_create :save_categories
  
   has_attached_file :cover, styles: {medium: "400x200" , :thumb => "100x100"}
   validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/

  def categories= (value)
  @categories = value

end

  def save_categories
    @categories.each do |category_id|
     HasCategory.create(category_id: category_id, products_id: self.id)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user! 	
  protect_from_forgery with: :exception
   include ApplicationHelper

  

 
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
   
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def index
  	@order= Order.all
  end

  def edit
  end

  def new

  end
 

  def show
  	@order= Order.all
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

  private
  def order_item_params
    params.require(:order_item).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.where(:user_id => current_user.id)
    @categoria = Category.all
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = current_user.products.new(product_params)
     @product.categories=params[:categories]
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def show

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    @category = Category.find(params[:product_id])
    @category.destroy
    
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:title, :price,:cantidad,:cover,:category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_item.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
	<ul>
		<% @order_item.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

<% if @order_items.size>0 %>
	<% @order_items.each do |item| %>
		<div class="well">
			<div class="row">
				<div class="col-sm-8">
					<h3><%= item.product.title %></h3>
				</div>
				<div class="col-sm-4">
					<div class="pull-right" onclick="location.reload()">
					<%= form_for(item, remote: true) do |f| %>
						<%= f.hidden_field :product_id, value: item.product.id %>
						<h5><%= item.product.price %></h5>
						<div class="form-group">
							<%= f.text_field :quantity, value: item.quantity.to_i, min: 1, class: 'form-control' %>
						</div>
						<div class="btn-group">
							<%= f.submit "Update Quantity", class: 'btn btn-primary' %>
							<%= link_to "Delete", item, method: :delete, remote: true, class: 'btn btn-danger'  %>
						</div>
			

					<% end %>
					</div>

				</div>
			</div>

		</div>
	<% end %>
	<div>
					
	<%= link_to  "Comprar #{current_order.subtotal}", 'order/index'  %>
			</div>
		
	
<% else %>
	
<% end %>

app/views/carts/show.html.erb
<div class="cart_item">
	<%= render "carts/cart_item" %>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.color_field :color, id: :category_color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>

</p>

<p>
  <strong>Color:</strong>
  <%= @category.color %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<h1>Products for sale</h1>
<% @products.each do |product| %>
	<div class="well">
		<div class="row">
			<div class="col-sm-8">
				<h3><%= product.title %></h3>

				<h3><%= image_tag product.cover.url()%></h3>
        
			</div>
			<div class="col-sm-4">
				<div class="pull-right" onclick="location.reload()">
				<%= form_for(@order_item, remote: true) do |f| %>
					<%= f.hidden_field :product_id, value: product.id %>
					<h5><%= product.price %></h5>
					<div class="form-group">
						<%= f.text_field :quantity, value: 1, min: 1, class: 'form-control' %>
					</div>
					<%= f.submit "Add to cart", class: 'btn btn-primary btn-sm'  %>
				<% end %>
				</div>
			</div>
		</div>	
    </div>
    
	</div>
	
<% end %>

app/views/order/edit.html.erb
<h1>Order#edit</h1>
<p>Find me in app/views/order/edit.html.erb</p>

app/views/order/index.html.erb
<h1>Gracias por su compra</h1>

app/views/order/new.html.erb
<h1>Order#new</h1>
<p>Find me in app/views/order/new.html.erb</p>

app/views/order/show.html.erb
<h1>Order</h1>
<div class="col-md-6 col-md-offset-3">
	<table class="table">
		<thead>
			<tr>
				<th>Numero</th>
				<th>Total</th>
     
			</tr>
		</thead>
		<tbody>
			<% @order.each do |product| %>
				<tr>
					<td><%= product.id %></td>
					<td><%= product.subtotal %></td>
					
          
				</tr>
			<% end %>
		</tbody>
	</table>
	

</div>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
	alert("Invalid")
<% else %>
	$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
$(".cart_item").html("<%= escape_javascript(render 'carts/cart_item') %>")

app/views/order_items/update.js.erb
$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
$(".cart_item").html("<%= escape_javascript(render 'carts/cart_item') %>")

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
	<div class="form-group">
		<%= f.label :title, "Title" %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :price, "Price" %>
		<%= f.number_field :price, value: 1, class: 'form-control', min: 1 %>
	</div>

	<div class="form-group">
		
		<%= f.file_field :cover %>
	</div>
    

   <label>Categorias </label>
<% @categories.each do |s|%>
    <div class="field">
      <%=check_box_tag "categories[]", s.id%> <%= s.name%>
    </div>

<%end%>

	<%= f.submit "Save", class: 'btn btn-success' %>
<% end %>
  

app/views/products/_forms.html.erb
<%= form_for(@product) do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price, "Price" %>
    <%= f.number_field :price, value: 1, class: 'form-control', min: 1 %>
  </div>
    <div class="form-group">
		
		<%= f.file_field :cover %>
	</div>



  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/products/edit.html.erb
<h3>Update product</h3>

<%= render 'forms' %>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to "New product", new_product_path %>

<div class="col-md-6 col-md-offset-3">
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>Price</th>
     
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<% @products.each do |product| %>
				<tr>
					<td><%= product.title %></td>
					<td><%= product.price %></td>
					<td><%= image_tag product.cover.url()%></td>
          
					<td>


						<%= link_to "Edit", edit_product_path(product) %>
						<%= link_to "Delete", product_path(product), method: :delete %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<% @categoria.each do |s|%>
    <div class="field">
      <%=check_box_tag "products[categories[]]", s.id%> <%= s.name%>
    </div>

<%end%>

</div>

app/views/products/new.html.erb
<h3>Create new product</h3>
<%= render 'form' %>