config/routes.rb
Rails.application.routes.draw do
  get 'order/index'

  get 'order/edit'

  get 'order/new'

  get 'order/show'

  

  resources :categories
  devise_for :users
  get 'home/index'

  resources :products
  resources :order_items
  resource :carts, only: [:show]

  root "home#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true
	 has_many :has_categories
	
end
 

app/models/has_category.rb
class HasCategory < ApplicationRecord
   has_and_belongs_to_many :products
  has_and_belongs_to_many :categories
 
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price*order_item.quantity) : 0}.sum
  end

  private
  def set_subtotal
    self[:subtotal] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :user
  has_many :order_items
  attr_reader :Categories

   after_create :save_categories
  
   has_attached_file :cover, styles: {medium: "400x200" , :thumb => "100x100"}
   validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/

  def categories= (value)
  @categories = value

end

  def save_categories
    @categories.each do |category_id|
     HasCategory.create(category_id: category_id, products_id: self.id)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :color)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
   
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def index
  	@order= Order.all
  end

  def edit
  end

  def new

  end
 

  def show
  	@order= Order.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.where(:user_id => current_user.id)
    @categoria = Category.all
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def create
    @product = current_user.products.new(product_params)
     @product.categories=params[:categories]
    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def show

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    @category = Category.find(params[:product_id])
    @category.destroy
    
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:title, :price,:cantidad,:cover,:category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items in card and price #{current_order.subtotal}", carts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">JUEGOS XD</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "Productos", root_path %></li>
              <li class="active"><%= link_to "Mis productos", Product %></li>
              <li class="active"><%= link_to "Categorias", Category %></li>
              <li class="active"><%= link_to "Compras", 'order/show' %></li>
              
            </ul>
            <ul class="nav navbar-nav navbar-right" >
              <li class="active cart"><%= render 'layouts/cart' %></li>
               <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>           </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
       <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
       <% end %>
    	<%= yield %>
    </div>
  </body>
</html>